objectives:
  lambda_importance: 1.0
  lambda_coverage: 0.8
  lambda_redundancy: 0.7
  length_penalty: 2.0
representations:
  use: true
  method: tfidf
  cache: true
candidates:
  use: true
  k: 15
  mode: hard
  sources:
  - score
  soft_boost: 1.05
  recall_target: null
redundancy:
  method: mmr
  lambda: 0.7
  sim_metric: cosine
length_control:
  unit: sentences
  max_tokens: 100
  max_sentences: 30
optimizer:
  method: nsga2
seed: 2024
features:
  weights:
    importance: 1.0
    length: 0.3
    position: 0.3
