representations:
  use: false

candidates:
  use: false

redundancy:
  method: mmr
  lambda: 0.7
  sim_metric: cosine

length_control:
  unit: sentences
  max_sentences: 20

optimizer:
  method: roberta

seed: 2024

bert:
  # Use local cache snapshot to avoid online downloads
  model_name: 'C:\\Users\\caspa\\.cache\\huggingface\\hub\\models--roberta-base\\snapshots\\e2da8e2f811d1448a5b465c236feacd80ffbac7b'
