# Stage1 Encoder (BERT) Top-K template
representations:
  use: false          # encoder ranking does not use precomputed similarity/candidates

candidates:
  use: false

redundancy:
  method: mmr
  lambda: 0.7
  sim_metric: cosine

length_control:
  unit: sentences
  max_sentences: 20

optimizer:
  method: bert       # or roberta/xlnet via CLI/config

seed: 2024

bert:
  model_name: bert-base-uncased
