# Archived: three-stage XLNet selector config (deprecated)
objectives:
  lambda_importance: 1.0
  lambda_coverage: 0.8
  lambda_redundancy: 0.7
representations:
  use: true
  method: "tfidf"
  cache: true
candidates:
  use: true
  k: 15
  mode: "hard"
  sources: ["score"]
redundancy:
  method: "mmr"
  lambda: 0.7
length_control:
  unit: "sentences"
  max_tokens: 100
  max_sentences: 3
nsga2:
  pop_size: 50
  n_gen: 100
three_stage:
  stage1_candidates: 10
  stage2_candidates: 10
  xlnet:
    model_name: "xlnet-base-cased"
optimizer:
  method: "three_stage_xlnet"
seed: 2024

