# Archived: three-stage RoBERTa selector config (deprecated)
objectives:
  lambda_importance: 1.0
  lambda_coverage: 0.8
  lambda_redundancy: 0.7
  length_penalty: 2.0
representations:
  use: true
  method: "tfidf"
  cache: true
candidates:
  use: true
  k: 15
  mode: "hard"
  sources: ["score"]
  soft_boost: 1.05
  recall_target: null
redundancy:
  method: "mmr"
  lambda: 0.7
  sim_metric: "cosine"
length_control:
  unit: "sentences"
  max_tokens: 100
  max_sentences: 3
nsga2:
  pop_size: 50
  n_gen: 100
three_stage:
  stage1_candidates: 10
  stage2_candidates: 10
  roberta:
    model_name: "roberta-base"
features:
  weights:
    importance: 1.0
    length: 0.3
    position: 0.3
optimizer:
  method: "three_stage_roberta"
seed: 2024

