representations:
  use: false

candidates:
  use: false

redundancy:
  method: mmr
  lambda: 0.7
  sim_metric: cosine

length_control:
  unit: sentences
  max_sentences: 20

optimizer:
  method: xlnet

seed: 2024

bert:
  # Use local cache snapshot to avoid online downloads
  model_name: 'C:\\Users\\caspa\\.cache\\huggingface\\hub\\models--xlnet-base-cased\\snapshots\\364e6ee6c9d8bd3b6f63a852cfd4fdc1d22d3674'

