representations:
  use: false

candidates:
  use: false

redundancy:
  method: mmr
  lambda: 0.7
  sim_metric: cosine

length_control:
  unit: sentences
  max_sentences: 5

optimizer:
  method: xlnet

seed: 2024

bert:
  # Use local cache snapshot to avoid online downloads
  model_name: 'C:/Users/caspa/.cache/huggingface/hub/models--xlnet-base-cased/merged_safetensors'

