objectives:
  lambda_importance: 1.0
  lambda_coverage: 0.8
  lambda_redundancy: 0.7
  length_penalty: 2.0
representations:
  use: true
  method: "tfidf"  # or "sbert"
  cache: true
candidates:
  use: true
  k: 15
  by: "score"      # or "title_sim"
redundancy:
  method: "mmr"    # or "jaccard"
  lambda: 0.7
  sim_metric: "cosine"
length_control:
  unit: "tokens"   # tokens | sentences
  max_tokens: 100
optimizer:
  method: "greedy" # greedy | grasp | nsga2 | bart | pegasus
seed: 2024
