features:
  tf: { use: true, norm: "log" }
  tf_isf: { use: true, ngram: 1, smooth: 1.0 }
  length: { use: true, type: "unique_tokens" }
  position: { use: true, lead_bonus: 0.2 }
  weights:
    tf: 0.4
    tf_isf: 0.4
    length: 0.1
    position: 0.1
  selection:
    max_tokens: 100
    redundancy_ngram: 3
    redundancy_threshold: 0.6

