objectives:
  lambda_importance: 1.0    # 重要性權重
  lambda_coverage: 0.8      # 覆蓋度權重（NSGA-II 標量化）
  lambda_redundancy: 0.7    # 冗餘懲罰權重（NSGA-II 標量化）

representations:
  use: true                 # 必須為 true，NSGA-II 需要相似度矩陣
  method: "tfidf"           # tfidf | sbert
  cache: true

candidates:
  use: true
  k: 15                     # 候選池大小
  mode: "hard"              # hard | soft
  sources: ["score"]        # 聯合集合：score | position | centrality

redundancy:
  method: "mmr"
  lambda: 0.7               # MMR 調和係數（alpha）

length_control:
  unit: "sentences"         # tokens | sentences
  max_tokens: 100
  max_sentences: 3          # 最終選出的句子數

# NSGA-II 參數
nsga2:
  pop_size: 50
  n_gen: 100

# 三階段系統特定配置
three_stage:
  stage1_candidates: 10     # NSGA-II 選出的候選數
  stage2_candidates: 10     # XLNet 選出的候選數
  xlnet:
    model_name: "xlnet-base-cased"  # 可選：xlnet-large-cased

optimizer:
  method: "three_stage_xlnet"

seed: 2024
