objectives:
  lambda_importance: 1.0
  lambda_coverage: 0.8
  lambda_redundancy: 0.7
  length_penalty: 2.0
representations:
  use: false
candidates:
  use: false
redundancy:
  method: mmr
  lambda: 0.6
  sim_metric: cosine
length_control:
  unit: sentences
  max_tokens: 100
  max_sentences: 3
optimizer:
  method: fused
seed: 2024
fusion:
  w_base: 0.0
  w_bert: 1.0
bert:
  model_name: bert-base-uncased
